version: 0.2

phases:
  install:
    commands:
      - echo Install phase started on `date`
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - gradlew -v
  build:
    commands:
      - echo Build phase started on `date`
      - ./gradlew clean
  post_build:
    commands:
      - echo Build completed on `date`

